name: TestCompile
on: [push, pull_request]
jobs:
  build:
    name: Test compiling for MKR1010
    runs-on: ubuntu-latest
    env:
      REQUIRED_LIBRARIES: Adafruit NeoPixel,ArduinoIoTCloud
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v2.0.0
      with:
          arduino-board-fqbn: arduino:samd:mkrwifi1010
          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
          sketch-name: Glowatch.ino