name: TestCompile

on: [push, pull_request]

jobs:
  build:
    name: Test compiling for MKR1010
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Arduino CLI version
        run: arduino-cli version

      - name: core update-index
        run: arduino-cli core update-index

      - name: lib update-index
        run: arduino-cli lib update-index

      - name: list-boards
        run: arduino-cli board list

      - name: install cores
        run: arduino-cli core install arduino:samd

      - name: install libraries
        run: arduino-cli lib install "Adafruit NeoPixel" ArduinoIoTCloud

      - name: compile
        run: arduino-cli compile --fqbn arduino:samd:mkrwifi1010 Glowatch
